#Example: production_general
# update_cycle: 20 the period of ticks between which factories are updated
# maintenance_cycle: 15 the period of ticks between which the maintenance of the factories are updated
# maintenance_rate: 1 %Modifies the rate at which factories degrade, higher numbers degrade the factories faster
#Example recipe entry with defaults included any section should be able to be excluded
# TITLE: (Don't use spaces, should be a unique identifier)
#   name: Default Name (Displayed name to user)
#   production_time: 1 (Time to produce the recipe)
#   inputs: (only include if there are inputs)
#     Common Name:
#       material: MATERIAL_NAME (Official bukkit material name)
#       amount: 1 (number of a particular item)
#       durability: 0 (damage value, 0 represents max durability, negative represents greater than max)
#       data: 0 (data value of the item stack
#       display_name: (display name of the item, null by default)
#       lore: (lore of the item, null by default)
#   upgrades: (only include if there are inputs)
#     Common Name:
#       material: MATERIAL_NAME (Official bukkit material name)
#       amount: 1 (number of a particular item)
#       durability: 0 (damage value, 0 represents max durability, negative represents greater than max)
#       data: 0 (data value of the item stack
#       display_name: (display name of the item, null by default)
#       lore: (lore of the item, null by default)
#   outputs: (only include if there are outputs)
#     Common Name:
#       material: MATERIAL_NAME (Official bukkit material name)
#       amount: 1 (number of a particular item)
#       durability: 0 (damage value, 0 represents max durability, negative represents greater than max)
#       data: 0 (data value of the item stack
#       display_name: (display name of the item, null by default)
#       lore: (lore of the item, null by default)
#   enchantments:
#     Common Name:
#       type: (Offificial bukkit enchantment name, Require)
#       level: 1 (level of the enchantment
#       probability: 1 (0-1 probability of the enchantment being applied)
#   output_recipes:
#     - TITLE (TITLE of the output recipe)
#   use_once: false (If this recipe is removed after its first use)
#   maintenance: 0 (Maximum amount of maintence required for this recipe)
######################################################################
#Example factory entry with defaults included any section should be able to be excluded
# TITLE: (Don't use spaces, should be a unique identifier)
#   name: Default Name (Displayed name to user)
#   fuel: (Defaults to charcoal if not present, only first entry used)
#     Common Name:
#       material: MATERIAL_NAME (Official bukkit material name)
#       amount: 1 (number of a particular item)
#       durability: 0 (damage value, 0 represents max durability, negative represents greater than max)
#       data: 0 (data value of the item stack
#       display_name: (display name of the item, null by default)
#       lore: (lore of the item, null by default)#   
#       lore: (lore of the item, null by default)#   fuel_time: 1 (Time that a piece of fuel lasts)
#   fuel_time: 1 (Time which fuel lasts)
#   inputs: (required)
#     Common Name:
#       material: MATERIAL_NAME (Official bukkit material name)
#       amount: 1 (number of a particular item)
#       durability: 0 (damage value, 0 represents max durability, negative represents greater than max)
#       data: 0 (data value of the item stack
#       display_name: (display name of the item, null by default)
#       lore: (lore of the item, null by default)
#   production_recipes:
#       - TITLE (title of recipe)
#   repair_material: (Defaults to coal if none are present)
#     Common Name:
#       material: MATERIAL_NAME (Official bukkit material name)
#       amount: 1 (number of a particular item)
#       durability: 0 (damage value, 0 represents max durability, negative represents greater than max)
#       data: 0 (data value of the item stack
#       display_name: (display name of the item, null by default)
#       lore: (lore of the item, null by default)
copy_defaults: false
general:
  central_block: WORKBENCH
  save_cycle: 15
  return_build_materials: false
  citadel_enabled: true
  factory_interaction_material: STICK
  disable_experience: true
production_general:
  update_cycle: 20
  repair_period: 28
  disrepair_period: 14
printing_presses:
  fuel:
    Charcoal:
      material: 'COAL'
      durability: 1
  fuel_time: 5
  costs:
     construction:
        "Iron block":
           material: 'IRON_BLOCK'
           amount: 60
        "Redstone":
           material: REDSTONE
           amount: 256
        "Quartz":
           material: QUARTZ
           amount: 64
        "Piston":
           material: PISTON_BASE
           amount: 20
        "Gold plate":
           material: GOLD_PLATE
           amount: 20
     plates:
        "Iron ingot":
           material: 'IRON_INGOT'
           amount: 1
        "Gold nugget":
           material: "GOLD_NUGGET"
           amount: 1
     set_page_time: 5
     repair:
        "Iron block":
           material: 'IRON_BLOCK'
           amount: 1
     repair_multiple: 5
     binding: # Each
        Leather:
           material: 'LEATHER'
           amount: 1
     page_lot:
        Paper:
           material: 'PAPER'
           amount: 4
        Ink:
           material: 'INK_SACK'
           durability: 0
           amount: 1
     pages_per_lot: 32
     page_lead: 6
     pamphlet_lot:
        Paper:
           material: 'PAPER'
           amount: 4
        Ink:
           material: 'INK_SACK'
           durability: 0
           amount: 1
     pamphlets_per_lot: 32
     security_lot:
        "Gold nuggets":
           material: 'GOLD_NUGGET'
           amount: 1
        "Cactus green":
           material: 'INK_SACK'
           durability: 2
           amount: 6
     security_notes_per_lot: 128

crafting:
  disable:
  enable:
    XP to Emerald:
      inputs:
        Exp Bottle:
          material: EXP_BOTTLE
          amount: 9
      output:
        Emerald:
          material: EMERALD
    Emerald to XP:
      inputs:
        Emerald:
          material: EMERALD
      output:
        Exp Bottle:
          material: EXP_BOTTLE
          amount: 9
    Stone to Double Slab:
      inputs:
        s:
         Stone:
           material: STONE
      shape:
        - sss
        - sss
      output:
        Double Stone Slab:
          material: DOUBLE_STEP
    Slab to Double Slab:
      inputs:
        s:
         Stone Slab:
           material: STEP
      shape:
        - s
        - s
      output:
        Double Stone Slab:
          material: DOUBLE_STEP
production_factories:
  Aspect_Factory:
    name: Arcane Elementizer
    fuel:
      Charcoal:
        material: COAL
        durability: 1
    inputs:
      Netherbrick:
        material: NETHER_BRICK
        amount: 1536
      Redstone:
        material: REDSTONE
        amount: 1152
      Netherquartz:
        material: QUARTZ
        amount: 576
    recipes:
      - Forge_Aspect_of_Terra
      - Forge_Aspect_of_End
      - Forge_Aspect_of_Nether
      - Craft_Eye_of_Ender
    repair_multiple: 26
    repair_inputs:
      Nether Brick:
        material: NETHER_BRICK
        amount: 6
      Redstone:
        material: REDSTONE
        amount: 5
      Netherquartz:
        material: QUARTZ
        amount: 2
nether_factory:
  name: Nether Factory
  fuel:
    Charcoal:
      material: COAL
      durability: 1
  costs:
    construction:
      Aspect of Nether:
        material: MAGMA_CREAM
        amount: 8
        display_name: Aspect of Nether
        lore: A concentrated essence of the Nether
      Aspect of Terra:
        material: DIAMOND
        amount: 8
        display_name: Aspect of Terra
        lore: A concentrated essence of Terra
      Aspect of END:
        material: FLINT
        amount: 8
        display_name: Aspect of End
        lore: A concentrated essence of the End
    repair:
       Diamond block:
         material: DIAMOND_BLOCK
         amount: 1
    repair_multiple: 1    
  fuel_time: 10
  repair_time: 12
  scaling_radius: 5000
  cost_scaling_radius: 5000
  use_fuel_on_teleport: false
production_recipes:
  Forge_Aspect_of_Terra:
    name: Forge Aspect of Terra
    production_time: 64
    inputs:
      Emerald Block:
        material: EMERALD_BLOCK
        amount: 24
      Diamond Block:
        material: DIAMOND_BLOCK
        amount: 24
      Gold Ore:
        material: GOLD_ORE
        amount: 8
      Slime Ball:
        material: SLIME_BALL
        amount: 8
      Anvil:
        material: ANVIL
        amount: 8
    outputs:
      Aspect of Terra:
        material: DIAMOND
        amount: 1
        display_name: Aspect of Terra
        lore: A concentrated essence of Terra
  Forge_Aspect_of_End:
    name: Forge Aspect of End
    production_time: 64
    inputs:
      Ender Pearl:
        material: ENDER_PEARL
        amount: 256
      Ender Chest:
        material: ENDER_CHEST
        amount: 256
      Endstone:
        material: ENDER_STONE
        amount: 1024
    outputs:
      Aspect of End:
        material: FLINT
        amount: 1
        display_name: Aspect of End
        lore: A concentrated essence of the End
  Forge_Aspect_of_Nether:
    name: Forge Aspect of Nether
    production_time: 64
    inputs:
      Ghast Tears:
        material: GHAST_TEAR
        amount: 16
      Quartz Ore:
        material: QUARTZ_ORE
        amount: 512
      Glowstone:
        material: GLOWSTONE
        amount: 512
    outputs:
      Aspect of Nether:
        material: MAGMA_CREAM
        amount: 1
        display_name: Aspect of Nether
        lore: A concentrated essence of the Nether
  Craft_Eye_of_Ender:
    name: Craft Eye of Ender
    production_time: 1
    inputs:
       Blaze Powder:
         material: BLAZE_POWDER
         amount: 265
       Ender Pearl:
         material: ENDER_PEARL
         amount: 265
    outputs:
       Eye of Ender:
         material: EYE_OF_ENDER
         amount: 256
